# Generated by Django 3.2.7 on 2022-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklist_app', '0003_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(),
        ),
    ]
